### ISSUE TITLE
ScanHost.update breaks as ssh-keyscan changed its API

### ISSUE THREAD

**Issue by jugmac00** [flyingcircusio/batou_ext#37]
ssh-keyscan now returns 1 (previously 0) when no keys are found

cf https://github.com/openssh/openssh-portable/commit/c2c18a39683db382a15b438632afab3f551d50ce

This broke my build on Travis when I updated to focal (Ubuntu 20.04).

**Ubuntu 18.04**
```
jugmac00@odin:~$ ssh-keyscan -6 github.com
getaddrinfo github.com: No address associated with hostname
getaddrinfo github.com: No address associated with hostname
getaddrinfo github.com: No address associated with hostname
jugmac00@odin:~$ echo $?
0
```

**Ubuntu 20.04**
```
jugmac00@heimdall:~$ ssh-keyscan -6 github.com
getaddrinfo github.com: No address associated with hostname
getaddrinfo github.com: No address associated with hostname
getaddrinfo github.com: No address associated with hostname
getaddrinfo github.com: No address associated with hostname
getaddrinfo github.com: No address associated with hostname
jugmac00@heimdall:~$ echo $?
1
```

P.S.: This is certainly no Ubuntu issue, I just used those distros as they provide ssh-keyscan versions before and after the above linked API change.

**Comment by frlan** [comment]
This is caused by https://github.com/flyingcircusio/batou_ext/blob/master/src/batou_ext/ssh.py#L100

To recover old -- silent failing -- behaviour something like 
```
try:
      self.cmd('ssh-keyscan -4 -p {} "{}" >> "{}"'.format(
                 self.port, self.hostname, self.known_hosts))
except:
    pass
try:
      self.cmd('ssh-keyscan -6 -p {} "{}" >> "{}"'.format(
                 self.port, self.hostname, self.known_hosts))
except:
    pass
```

could do the trick -- but feels a little clunky

**Comment by jugmac00** [comment]
From a gut feeling, I would suggest to make the scan process configurable, ie tell it to use IPv4, IPv6 or both.

That would also mean that `SSHKeyPair` needs to be configurable, and then pass the desired internet protocol down to `ScanHost`.

https://github.com/flyingcircusio/batou_ext/blob/e8ce1e8084e450b41aa5be715e184afd33357531/src/batou_ext/ssh.py#L60-L62

**Comment by jugmac00** [comment]
@zagy Thanks for the fix.
